language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "jastajvirdee-github"
    token:
      secure: "cf6ec8f93bd17ef8ee2b9e1283931aa87afefd90"


jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
